version: '3'

# this is alias 
x-airflow-common:
  &airflow-common
  image: apache/airflow:2.8.1-python3.11
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+pymysql://root:meowmeow@backend_database/defaultdb
    - AIRFLOW__CORE__FERNET_KEY=FB0o_zt4e3Ziq3LdUUO7F2Z95cvFFx16hU8jTeR1ASM=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOGGING_LEVEL=INFO
  volumes:
    - ./dags:/opt/airflow/dags
    - ./airflow-data/logs:/opt/airflow/logs
    - ./airflow-data/plugins:/opt/airflow/plugins
    - ./airflow.cfg:/opt/airlfow/airflow.cfg
  depends_on:
    - backend_database
    - wikidump_database


services:
  backend_database: 
    # connection string is: 
    # mysql://root:meowmeow@localhost:7775/defaultdb
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: meowmeow
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: root
      MYSQL_PASSWORD: meowmeow
    ports:
      - "7775:3306" # export port 7775 to outside
  
  wikidump_database:
    # mysql://root:meowmeow@localhost:7776/defaultdb
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: meowmeow
      MYSQL_DATABASE: defaultdb
      MYSQL_USER: root
      MYSQL_PASSWORD: meowmeow
    ports:
      - "7776:3306" # export port 7776 to outside

  airflow-init:
    << : *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - airflow users list || ( airflow db init &&
        airflow users create
          --role Admin
          --username airflow
          --password airflow
          --email airflow@airflow.com
          --firstname airflow
          --lastname airflow )
    restart: on-failure


  airflow-webserver:
    << : *airflow-common
    command: airflow webserver
    ports:
      - 8080:8080
    container_name: airflow_webserver
    restart: always

  airflow-scheduler:
    << : *airflow-common
    command: airflow scheduler
    container_name: airflow_scheduler
    restart: always
